export interface Product {
  id: number;
  name: string;
  category: string;
  price: number;
  brand: string;
  image: string;
}

export const products: Product[] = [
  { id: 1, name: 'Fender Stratocaster American Pro', category: 'Guitarras', price: 2850000, brand: 'Fender', image: '/productos/fender-stratocaster-pro.jpg' },
  { id: 2, name: 'Gibson Les Paul Standard', category: 'Guitarras', price: 4200000, brand: 'Gibson', image: '/productos/gibson-lespaul.jpg' },
  { id: 12, name: 'Ibanez GRG121DX', category: 'Guitarras', price: 620000, brand: 'Ibanez', image: '/productos/ibanez-grg121.jpg' },
  { id: 13, name: 'Fender Telecaster Player', category: 'Guitarras', price: 1450000, brand: 'Fender', image: '/productos/fender-stratocaster-pro.jpg' },
  { id: 14, name: 'Gibson SG Standard', category: 'Guitarras', price: 2100000, brand: 'Gibson', image: '/productos/gibson-sg.jpg' },
  { id: 15, name: 'Ibanez RG421', category: 'Guitarras', price: 780000, brand: 'Ibanez', image: '/productos/ibanez-rg421.jpg' },
  { id: 16, name: 'Yamaha Pacifica 112V', category: 'Guitarras', price: 520000, brand: 'Yamaha', image: '/productos/yamaha-pacifica.jpg' },
  { id: 17, name: 'Epiphone Les Paul Standard', category: 'Guitarras', price: 890000, brand: 'Epiphone', image: '/productos/epiphone-lespaul.jpg' },
  { id: 18, name: 'PRS SE Custom 24', category: 'Guitarras', price: 1650000, brand: 'PRS', image: '/productos/prs-se-custom.jpg' },
  { id: 19, name: 'Jackson JS32 Dinky', category: 'Guitarras', price: 680000, brand: 'Jackson', image: '/productos/jackson-dinky.jpg' },
  { id: 3, name: 'Ibanez SR300E Bass', category: 'Bajos', price: 890000, brand: 'Ibanez', image: '/productos/ibanez-sr300.jpg' },
  { id: 4, name: 'Fender Precision Bass', category: 'Bajos', price: 1650000, brand: 'Fender', image: '/productos/fender-precision.jpg' },
  { id: 20, name: 'Fender Jazz Bass', category: 'Bajos', price: 1750000, brand: 'Fender', image: '/productos/fender-jazz.jpg' },
  { id: 21, name: 'Ibanez GSR200', category: 'Bajos', price: 520000, brand: 'Ibanez', image: '/productos/ibanez-gsr200.jpg' },
  { id: 22, name: 'Yamaha TRBX174', category: 'Bajos', price: 450000, brand: 'Yamaha', image: '/productos/yamaha-trbx174.jpg' },
  { id: 23, name: 'Epiphone Thunderbird', category: 'Bajos', price: 780000, brand: 'Epiphone', image: '/productos/epiphone-thunderbird.jpg' },
  { id: 24, name: 'Sterling by Music Man SUB Ray4', category: 'Bajos', price: 620000, brand: 'Sterling by Music Man', image: '/productos/musicman-ray4.jpg' },
  { id: 5, name: 'Pearl Export EXX725', category: 'Bateria', price: 1200000, brand: 'Pearl', image: '/productos/pearl-export.jpg' },
  { id: 6, name: 'Yamaha Stage Custom', category: 'Bateria', price: 1450000, brand: 'Yamaha', image: '/productos/yamaha-stage.jpg' },
  { id: 25, name: 'Tama Imperialstar', category: 'Bateria', price: 1350000, brand: 'Tama', image: '/productos/tama-imperialstar.jpg' },
  { id: 26, name: 'Pearl Roadshow', category: 'Bateria', price: 850000, brand: 'Pearl', image: '/productos/pearl-roadshow.jpg' },
  { id: 27, name: 'Yamaha GigMaker', category: 'Bateria', price: 920000, brand: 'Yamaha', image: '/productos/yamaha-gigmaker.jpg' },
  { id: 28, name: 'Mapex Tornado', category: 'Bateria', price: 780000, brand: 'Mapex', image: '/productos/mapex-tornado.jpg' },
  { id: 7, name: 'Roland FP-30X Digital', category: 'Teclados', price: 980000, brand: 'Roland', image: '/productos/roland-fp30x.jpg' },
  { id: 8, name: 'Yamaha PSR-E373', category: 'Teclados', price: 450000, brand: 'Yamaha', image: '/productos/yamaha-psre373.jpg' },
  { id: 29, name: 'Casio CT-S300', category: 'Teclados', price: 380000, brand: 'Casio', image: '/productos/casio-cts300.jpg' },
  { id: 30, name: 'Korg B2 Digital Piano', category: 'Teclados', price: 850000, brand: 'Korg', image: '/productos/korg-b2.jpg' },
  { id: 31, name: 'Yamaha P-45', category: 'Teclados', price: 720000, brand: 'Yamaha', image: '/productos/yamaha-p45.jpg' },
  { id: 32, name: 'Roland GO:KEYS', category: 'Teclados', price: 650000, brand: 'Roland', image: '/productos/roland-gokeys.jpg' },
  { id: 33, name: 'Korg Microkey 61', category: 'Teclados', price: 420000, brand: 'Korg', image: '/productos/korg-microkey.jpg' },
  { id: 11, name: 'Yamaha YTS-280 Saxofon', category: 'Vientos', price: 1350000, brand: 'Yamaha', image: '/productos/yamaha-yts280.jpg' },
  { id: 34, name: 'Yamaha YTR-2330 Trompeta', category: 'Vientos', price: 980000, brand: 'Yamaha', image: '/productos/yamaha-ytr2330.jpg' },
  { id: 35, name: 'Bach Stradivarius Trombon', category: 'Vientos', price: 2100000, brand: 'Bach', image: '/productos/bach-trombon.jpg' },
  { id: 36, name: 'Yamaha YCL-255 Clarinete', category: 'Vientos', price: 1150000, brand: 'Yamaha', image: '/productos/yamaha-ycl255.jpg' },
  { id: 37, name: 'Jean Paul USA Flauta', category: 'Vientos', price: 420000, brand: 'Jean Paul USA', image: '/productos/jeanpaul-flauta.jpg' },
  { id: 84, name: 'Yamaha YRS-302B Flauta Dulce', category: 'Vientos', price: 45000, brand: 'Yamaha', image: '/productos/yamaha-yrs302.jpg' },
  { id: 85, name: 'Aulos 309 Flauta Dulce', category: 'Vientos', price: 38000, brand: 'Aulos', image: '/productos/aulos-309.jpg' },
  { id: 86, name: 'Buffet E11 Clarinete', category: 'Vientos', price: 2100000, brand: 'Buffet', image: '/productos/buffet-e11.jpg' },
  { id: 87, name: 'Yamaha YCL-450 Clarinete', category: 'Vientos', price: 1850000, brand: 'Yamaha', image: '/productos/yamaha-ycl450.jpg' },
  { id: 88, name: 'Yamaha YOB-241 Oboe', category: 'Vientos', price: 3200000, brand: 'Yamaha', image: '/productos/yamaha-yob241.jpg' },
  { id: 89, name: 'Yamaha YFG-811 Fagot', category: 'Vientos', price: 8500000, brand: 'Yamaha', image: '/productos/yamaha-yfg811.jpg' },
  { id: 90, name: 'Yamaha YHR-322II Trompa', category: 'Vientos', price: 2800000, brand: 'Yamaha', image: '/productos/yamaha-yhr322.jpg' },
  { id: 91, name: 'Yamaha YBB-321 Tuba', category: 'Vientos', price: 6500000, brand: 'Yamaha', image: '/productos/yamaha-ybb321.jpg' },
  { id: 92, name: 'Yamaha YAS-280 Saxo Alto', category: 'Vientos', price: 1650000, brand: 'Yamaha', image: '/productos/yamaha-yas280.jpg' },
  { id: 93, name: 'Selmer AS500 Saxo Alto', category: 'Vientos', price: 2800000, brand: 'Selmer', image: '/productos/selmer-as500.jpg' },
  { id: 94, name: 'Yamaha YTS-480 Saxo Tenor', category: 'Vientos', price: 2400000, brand: 'Yamaha', image: '/productos/yamaha-yts480.jpg' },
  { id: 9, name: 'Shure SM58-LCE', category: 'Sonido', price: 185000, brand: 'Shure', image: '/productos/shure-sm58.jpg' },
  { id: 10, name: 'Audio-Technica AT2020', category: 'Sonido', price: 220000, brand: 'Audio-Technica', image: '/productos/audiotechnica-at2020.jpg' },
  { id: 38, name: 'Shure SM57', category: 'Sonido', price: 175000, brand: 'Shure', image: '/productos/shure-sm57.jpg' },
  { id: 39, name: 'Audio-Technica ATH-M50x', category: 'Sonido', price: 320000, brand: 'Audio-Technica', image: '/productos/audiotechnica-m50x.jpg' },
  { id: 40, name: 'Behringer U-Phoria UM2', category: 'Sonido', price: 145000, brand: 'Behringer', image: '/productos/behringer-um2.jpg' },
  { id: 41, name: 'Focusrite Scarlett Solo', category: 'Sonido', price: 380000, brand: 'Focusrite', image: '/productos/focusrite-solo.jpg' },
  { id: 42, name: 'AKG P420', category: 'Sonido', price: 280000, brand: 'AKG', image: '/productos/akg-p420.jpg' },
  { id: 43, name: 'Rode NT1-A', category: 'Sonido', price: 420000, brand: 'Rode', image: '/productos/rode-nt1a.jpg' },
  { id: 44, name: 'Yamaha U1 Piano Vertical', category: 'Pianos', price: 8500000, brand: 'Yamaha', image: '/productos/yamaha-u1.jpg' },
  { id: 45, name: 'Kawai K-300 Piano Vertical', category: 'Pianos', price: 7800000, brand: 'Kawai', image: '/productos/kawai-k300.jpg' },
  { id: 46, name: 'Yamaha C1X Piano de Cola', category: 'Pianos', price: 25000000, brand: 'Yamaha', image: '/productos/yamaha-c1x.jpg' },
  { id: 47, name: 'Roland LX-708 Digital', category: 'Pianos', price: 4200000, brand: 'Roland', image: '/productos/roland-lx708.jpg' },
  { id: 48, name: 'Kawai CA99 Digital', category: 'Pianos', price: 3800000, brand: 'Kawai', image: '/productos/kawai-ca99.jpg' },
  { id: 49, name: 'Nord Piano 5 Stage', category: 'Pianos', price: 5200000, brand: 'Nord', image: '/productos/nord-piano5.jpg' },
  { id: 50, name: 'Yamaha V5SA Violin 4/4', category: 'Violines', price: 850000, brand: 'Yamaha', image: '/productos/yamaha-v5sa.jpg' },
  { id: 51, name: 'Stentor Student II Violin', category: 'Violines', price: 420000, brand: 'Stentor', image: '/productos/stentor-student.jpg' },
  { id: 52, name: 'Cremona SV-175 Violin', category: 'Violines', price: 680000, brand: 'Cremona', image: '/productos/cremona-sv175.jpg' },
  { id: 53, name: 'Knilling Perfection Violin', category: 'Violines', price: 1200000, brand: 'Knilling', image: '/productos/knilling-perfection.jpg' },
  { id: 54, name: 'Yamaha V7SG Violin', category: 'Violines', price: 1850000, brand: 'Yamaha', image: '/productos/yamaha-v7sg.jpg' },
  { id: 55, name: 'Yamaha VC5S Violinchelo 4/4', category: 'Violinchelos', price: 1650000, brand: 'Yamaha', image: '/productos/yamaha-vc5s.jpg' },
  { id: 56, name: 'Stentor Cello 4/4', category: 'Violinchelos', price: 980000, brand: 'Stentor', image: '/productos/stentor-cello.jpg' },
  { id: 57, name: 'Knilling 134VC Violinchelo', category: 'Violinchelos', price: 2100000, brand: 'Knilling', image: '/productos/knilling-cello.jpg' },
  { id: 58, name: 'Yamaha VA5 Viola 16"', category: 'Violas', price: 920000, brand: 'Yamaha', image: '/productos/yamaha-va5.jpg' },
  { id: 59, name: 'Cremona SV-150 Viola', category: 'Violas', price: 750000, brand: 'Cremona', image: '/productos/cremona-viola.jpg' },
  { id: 60, name: 'Stentor Bass 3/4', category: 'Contrabajo', price: 2800000, brand: 'Stentor', image: '/productos/stentor-bass.jpg' },
  { id: 61, name: 'Yamaha SLB200 Silent Bass', category: 'Contrabajo', price: 4500000, brand: 'Yamaha', image: '/productos/yamaha-slb200.jpg' },
  { id: 62, name: 'LP Aspire Congas', category: 'Percusion', price: 680000, brand: 'LP', image: '/productos/lp-congas.jpg' },
  { id: 63, name: 'Meinl Bongos', category: 'Percusion', price: 320000, brand: 'Meinl', image: '/productos/meinl-bongos.jpg' },
  { id: 64, name: 'Cajon Peruano Professional', category: 'Percusion', price: 280000, brand: 'Pearl', image: '/productos/cajon-peruano.jpg' },
  { id: 65, name: 'Pearl PFB-200 Bongos', category: 'Percusion', price: 380000, brand: 'Pearl', image: '/productos/pearl-bongos.jpg' },
  { id: 66, name: 'LP Galaxia Timbales', category: 'Percusion', price: 850000, brand: 'LP', image: '/productos/lp-timbales.jpg' },
  { id: 67, name: 'Meinl Djembe 12"', category: 'Percusion', price: 420000, brand: 'Meinl', image: '/productos/meinl-djembe.jpg' },
  { id: 68, name: 'Hohner Bravo III 72', category: 'Acordeon', price: 1850000, brand: 'Hohner', image: '/productos/hohner-bravo.jpg' },
  { id: 69, name: 'Pigini M1 Piano', category: 'Acordeon', price: 3200000, brand: 'Pigini', image: '/productos/pigini-m1.jpg' },
  { id: 70, name: 'Victoria 402 PM', category: 'Acordeon', price: 2800000, brand: 'Victoria', image: '/productos/victoria-402.jpg' },
  { id: 71, name: 'Kala KA-S Soprano', category: 'Ukelele', price: 180000, brand: 'Kala', image: '/productos/kala-soprano.jpg' },
  { id: 72, name: 'Fender Venice Soprano', category: 'Ukelele', price: 220000, brand: 'Fender', image: '/productos/fender-venice.jpg' },
  { id: 73, name: 'Cordoba 15CM Concert', category: 'Ukelele', price: 280000, brand: 'Cordoba', image: '/productos/cordoba-15cm.jpg' },
  { id: 74, name: 'Kala KA-T Tenor', category: 'Ukelele', price: 320000, brand: 'Kala', image: '/productos/kala-tenor.jpg' },
  { id: 75, name: 'Deering Goodtime Banjo', category: 'Banjo', price: 850000, brand: 'Deering', image: '/productos/deering-goodtime.jpg' },
  { id: 76, name: 'Gold Tone AC-1 Banjo', category: 'Banjo', price: 620000, brand: 'Gold Tone', image: '/productos/goldtone-ac1.jpg' },
  { id: 77, name: 'Ibanez M510 Mandolina', category: 'Mandolina', price: 420000, brand: 'Ibanez', image: '/productos/ibanez-m510.jpg' },
  { id: 78, name: 'Kentucky KM-150 Mandolina', category: 'Mandolina', price: 780000, brand: 'Kentucky', image: '/productos/kentucky-km150.jpg' },
  { id: 79, name: 'Hohner Marine Band', category: 'Armonica', price: 85000, brand: 'Hohner', image: '/productos/hohner-marine.jpg' },
  { id: 80, name: 'Suzuki Promaster', category: 'Armonica', price: 120000, brand: 'Suzuki', image: '/productos/suzuki-promaster.jpg' },
  { id: 81, name: 'Hohner Special 20', category: 'Armonica', price: 95000, brand: 'Hohner', image: '/productos/hohner-special20.jpg' },
  { id: 82, name: 'Rees Harps Sharpsicle', category: 'Arpa', price: 1200000, brand: 'Rees Harps', image: '/productos/rees-sharpsicle.jpg' },
  { id: 83, name: 'Dusty Strings Harpsicle', category: 'Arpa', price: 1850000, brand: 'Dusty Strings', image: '/productos/dusty-harpsicle.jpg' },
];

export const categories = Array.from(new Set(products.map((product) => product.category)));

export const brands = Array.from(new Set(products.map((product) => product.brand))).sort((a, b) =>
  a.localeCompare(b, 'es')
);

export const maxCatalogPrice = Math.ceil(Math.max(...products.map((product) => product.price)) / 1000000) * 1000000;
